version: "3.8"

services:
  unitrade_db:
    image: mariadb:10.6.3
    container_name: unitrade_db
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=True
    env_file:
      - /app/.env
    restart: on-failure
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql`
    networks:
      - separated_network

volumes:
  db_data:
  manticore_data:

networks:
  separated_network: